/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ar.com.grupoesfera.capacitacion.enviospostales;
import java.security.InvalidParameterException;


public class Despachador {
    int numeropaquetes;
    int peso;
    int numeroenvio;
    double costo;

    public Despachador (int numeropaquetes, int peso){
        this.numeropaquetes = numeropaquetes;
        this.peso = peso;
        this.numeroenvio = 0;
        this.costo = 0.0;
    }
    public double obtenercosto(){
        return this.costo;
    }
    public void calculadorcostos (int numeropaquetes, int numeroenvio){
        if (numeropaquetes < 1) {
            throw new InvalidParameterException("Es necesario enviar al menos 1 paquete");
        }
        double costoadministrativo = 1;
        if (numeroenvio >= 10){
            costoadministrativo = 1.1;
        }
        this.numeroenvio = numeroenvio + 1;
        if (numeropaquetes <= 5) {
            this.costo = 50 * costoadministrativo;
        } else if (numeropaquetes <= 10) {
            this.costo = 80 * costoadministrativo;
        } else {
            this.costo = (80 + ((numeropaquetes - 10) * 15))* costoadministrativo;
        }
    }

    public String asignacionvehiculo (int peso){
        if (peso <= 5){
            return "Bicicleta";
        } else if (peso <= 50){
            return "Automovil";
        } else if (peso <= 150){
            return "Camionta";
        } else {
            return "No se puede asignar Vehiculo";
        }
    }

}
